//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

namespace RobotAI
{
		public class CircuitRefs
		{
			public static List<WaypointCircuit> courses = new List<WaypointCircuit>();

			public static WaypointCircuit getClosestCourse(Vector3 point){
				int i = 0;
				float cDist;
				WaypointCircuit closest = courses[0];
				float dist = closestDistance(closest, point);
				cDist = dist;
				for(i = 1; i < courses.Count; ++i){
					cDist = closestDistance(courses[i], point);
					if (cDist < dist){
						dist = cDist;
						closest = courses[i];
					}
				}
				return closest;
			}

			private static float closestDistance(WaypointCircuit c, Vector3 pt){
				int i = 0;
				int l = c.waypointList.items.Length;
				Transform[] pts = c.Waypoints;
				float dis  = Vector3.Distance(c.Waypoints[0].position, pt);
				for (i = 1; i < l; ++i){
					if (Vector3.Distance(c.Waypoints[i].position, pt) < dis){
						dis = Vector3.Distance(c.Waypoints[i].position, pt);
					}
				}
				return dis;
			}
		}
}

